version: '3.7'

services:
  web:
    build: .
    command: sh -c "python /code/users_generator.py &&
      python /code/app.py"
    volumes:
      - .:/code
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data5/
volumes:
  postgres_data:

